---
autoinstallver: 1
name: builder-node
version: 0.01
tests: t/
test_script: test.sh
type: nodeunit

excludedir:
    - t
    - node_modules
    - app
    - bower_components
    - script
    - robohydra

# debian packages that the tests requires to run.
test_requires:
    - libmoosex-getopt-perl
    - startsiden-nodejs
    - libfreetype6
    - libfontconfig1
    - libpng12-0
    - rubygems
    - git


