---
autoinstallver: 1
name: builder-node
version: 0.01
tests: spec/ t/
test_command: perl jasmine_plus_perl.pl

excludedir:
    - t
    - node_modules
    - app
    - bower_components
    - script
    - robohydra

# debian packages that the tests requires to run.
test_requires:
    - libfile-find-rule-perl
    - libarchive-tar-perl
    - libfile-slurp-perl
    - libfile-basename-perl
    - cpan-libtap-simpleoutput-perl
    - libmoosex-getopt-perl
    - startsiden-nodejs
    - libfreetype6
    - libfontconfig1
    - libpng12-0
    - rubygems
    - git


