---
autoinstallver: 1
name: builder-node
version: 0.01
tests: t/
test_script: test.sh
type: nodeunit

# debian packages that the tests requires to run.
test_requires:
    - startsiden-nodejs
    - libfreetype6
    - libfontconfig1
    - libpng12-0
    - rubygems
    - git


