---
autoinstallver: 1
name: builder-node
version: 0.01
tests: spec/
test_command: prove -m -a /archive.tgz --exec ./jasmine_tap --ext .js -r -v spec

excludedir:
    - t
    - node_modules
    - app
    - bower_components
    - script
    - robohydra

# debian packages that the tests requires to run.
test_requires:
    - cpan-libtap-simpleoutput-perl
    - libmoosex-getopt-perl
    - startsiden-nodejs
    - libfreetype6
    - libfontconfig1
    - libpng12-0
    - rubygems
    - git


